In [1]:
# import all EDA libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('/Users/shivam13juna/Documents/scaler/AIML_mlops/sep_2026/v1-aiml-mlops/lec-2 Optuna and Streamlit/data/cars24-car-price.csv')
df.head()

,full_name,selling_price,year,seller_type,km_driven,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Maruti Alto Std,1.20,2012.0,Individual,120000,Petrol,Manual,19.70,796.0,46.30,5.0
1,Hyundai Grand i10 Asta,5.50,2016.0,Individual,20000,Petrol,Manual,18.90,1197.0,82.00,5.0
2,Hyundai i20 Asta,2.15,2010.0,Individual,60000,Petrol,Manual,17.00,1197.0,80.00,5.0
3,Maruti Alto K10 2010-2014 VXI,2.26,2012.0,Individual,37000,Petrol,Manual,20.92,998.0,67.10,5.0
4,Ford Ecosport 2015-2021 1.5 TDCi Titanium BSIV,5.70,2015.0,Dealer,30000,Diesel,Manual,22.77,1498.0,98.59,5.0

In [3]:
# label encode fuel_type using below
encode_dict={
    "fuel_type": {"Diesel": 1, "Petrol": 2, "CNG": 3, "LPG": 4, "Electric": 5},
     "transmission_type": {"Manual": 1, "Automatic": 2},
	 "seller_type": {"Dealer": 1, "Individual": 2, "Trustmark Dealer": 3}

     }

df.replace(encode_dict, inplace=True)
df.head()

/var/folders/p6/6_nprx9x22s4njm57gzb34l40000gp/T/ipykernel_13675/1083671936.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(encode_dict, inplace=True)

,full_name,selling_price,year,seller_type,km_driven,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Maruti Alto Std,1.20,2012.0,2,120000,2,1,19.70,796.0,46.30,5.0
1,Hyundai Grand i10 Asta,5.50,2016.0,2,20000,2,1,18.90,1197.0,82.00,5.0
2,Hyundai i20 Asta,2.15,2010.0,2,60000,2,1,17.00,1197.0,80.00,5.0
3,Maruti Alto K10 2010-2014 VXI,2.26,2012.0,2,37000,2,1,20.92,998.0,67.10,5.0
4,Ford Ecosport 2015-2021 1.5 TDCi Titanium BSIV,5.70,2015.0,1,30000,1,1,22.77,1498.0,98.59,5.0

In [4]:
df.shape

(19980, 11)

In [5]:
features = ['year', 'seller_type', 'km_driven', 'fuel_type', 'transmission_type', 'mileage', 'engine', 'max_power', 'seats']
target = ['selling_price']

X = df[features]
y = df[target]

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [7]:

import joblib
joblib.dump(scaler, 'scaler.pkl') # it supports distributed computing

['scaler.pkl']

In [8]:
#import pickle

#with open('scaler.pkl', 'wb') as f:
#    pickle.dump(scaler, f)

In [9]:
#scaler = joblib.load('scaler.pkl')

In [10]:
# print mean and std of every column
print(scaler.mean_) # mean
print(scaler.scale_) # standard deviation

[2.01452513e+03 1.41026026e+00 5.82448790e+04 1.53318318e+00
 1.19774775e+00 1.93472187e+01 1.47632740e+03 9.78544432e+01
 5.31786787e+00]
[3.24910388e+00 5.10848116e-01 5.17237960e+04 5.55660630e-01
 3.98300861e-01 4.61993714e+00 5.20436374e+02 4.50795416e+01
 8.35349548e-01]

In [11]:
from xgboost import XGBRegressor
model = XGBRegressor()
model.fit(X, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [12]:
joblib.dump(model, 'cars24_model.joblib')

import pickle

with open('cars24_model.pkl', 'wb') as f:
    pickle.dump(model, f)

In [13]:
# calculate some metrics

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
y_pred = model.predict(X)
mae = mean_absolute_error(y, y_pred)
mse = mean_squared_error(y, y_pred)
r2 = r2_score(y, y_pred)

print(f'Mean Absolute Error: {mae}')
print(f'Mean Squared Error: {mse}')
print(f'R2 Score: {r2}')

Mean Absolute Error: 0.727061927318573
Mean Squared Error: 1.274588942527771
R2 Score: 0.9846179485321045